// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KallpaNexus.Infrastructure.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260522172810_SyncApplicationModel")]
    partial class SyncApplicationModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KallpaNexus.Domain.Entities.Compartido.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioConsumidorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioConsumidorId");

                    b.HasIndex("TenantId", "Dni")
                        .IsUnique();

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Entities.Cancha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("EstaActiva")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TieneIluminacion")
                        .HasColumnType("boolean");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId");

                    b.ToTable("Canchas");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Entities.CanchaTarifa", b =>
                {
                    b.Property<Guid>("CanchaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TarifaCanchaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("CanchaId", "TarifaCanchaId");

                    b.HasIndex("TarifaCanchaId");

                    b.ToTable("CanchasTarifas", (string)null);
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Entities.MedioPagoTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("ConfiguracionIntegracionJson")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("EsPasarelaExterna")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<bool>("PermiteSinVoucherPresencial")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiereVoucherOnline")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("MediosPago", (string)null);
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Entities.PagoReserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Canal")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoOperacion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<Guid>("MedioPagoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<bool>("RegistradoSinVoucher")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ReservaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("VoucherUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("MedioPagoId");

                    b.HasIndex("ReservaId");

                    b.HasIndex("TenantId");

                    b.ToTable("PagosReserva", (string)null);
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Entities.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CanchaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("HoraFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("numeric");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CanchaId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Entities.Sucursal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TelefonoWhatsApp")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Sucursales", (string)null);
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Entities.TarifaCancha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<bool>("AplicaFinDeSemana")
                        .HasColumnType("boolean");

                    b.Property<bool>("AplicaLunesAViernes")
                        .HasColumnType("boolean");

                    b.Property<int>("HoraFin")
                        .HasColumnType("integer");

                    b.Property<int>("HoraInicio")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PrecioPorHora")
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("TarifasCanchas", (string)null);
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Tenancy.RolTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("EsSistema")
                        .HasColumnType("boolean");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Codigo")
                        .IsUnique();

                    b.ToTable("RolesTenant", (string)null);
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Tenancy.RolTenantPermiso", b =>
                {
                    b.Property<Guid>("RolTenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("PermisoCodigo")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("RolTenantId", "PermisoCodigo");

                    b.ToTable("RolesTenantPermisos", (string)null);
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Tenancy.UsuarioStaff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RolTenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RolTenantId");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("UsuariosStaff", (string)null);
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Entities.Cancha", b =>
                {
                    b.HasOne("KallpaNexus.Domain.Modulos.Sport.Entities.Sucursal", "Sucursal")
                        .WithMany("Canchas")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Entities.CanchaTarifa", b =>
                {
                    b.HasOne("KallpaNexus.Domain.Modulos.Sport.Entities.Cancha", "Cancha")
                        .WithMany()
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KallpaNexus.Domain.Modulos.Sport.Entities.TarifaCancha", "TarifaCancha")
                        .WithMany()
                        .HasForeignKey("TarifaCanchaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cancha");

                    b.Navigation("TarifaCancha");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Entities.PagoReserva", b =>
                {
                    b.HasOne("KallpaNexus.Domain.Modulos.Sport.Entities.MedioPagoTenant", "MedioPago")
                        .WithMany()
                        .HasForeignKey("MedioPagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KallpaNexus.Domain.Modulos.Sport.Entities.Reserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedioPago");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Entities.Reserva", b =>
                {
                    b.HasOne("KallpaNexus.Domain.Modulos.Sport.Entities.Cancha", "Cancha")
                        .WithMany()
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KallpaNexus.Domain.Entities.Compartido.Cliente", "Cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cancha");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Tenancy.RolTenantPermiso", b =>
                {
                    b.HasOne("KallpaNexus.Domain.Modulos.Sport.Tenancy.RolTenant", "RolTenant")
                        .WithMany("Permisos")
                        .HasForeignKey("RolTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RolTenant");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Tenancy.UsuarioStaff", b =>
                {
                    b.HasOne("KallpaNexus.Domain.Modulos.Sport.Tenancy.RolTenant", "RolTenant")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolTenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RolTenant");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Entities.Compartido.Cliente", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Entities.Sucursal", b =>
                {
                    b.Navigation("Canchas");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Tenancy.RolTenant", b =>
                {
                    b.Navigation("Permisos");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
