// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KallpaNexus.Infrastructure.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260612145701_SucursalCoordenadas")]
    partial class SucursalCoordenadas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KallpaNexus.Domain.Entities.Compartido.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioConsumidorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioConsumidorId");

                    b.HasIndex("TenantId", "Dni")
                        .IsUnique();

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("KallpaNexus.Domain.Integraciones.ConsultaSunatRucCache", b =>
                {
                    b.Property<string>("NumeroRuc")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("Condicion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ConsultadoEnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Distrito")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsDatosCompletos")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadBasicoJson")
                        .HasColumnType("text");

                    b.Property<string>("PayloadCompletoJson")
                        .HasColumnType("text");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("NumeroRuc");

                    b.ToTable("ConsultasSunatRuc", (string)null);
                });

            modelBuilder.Entity("KallpaNexus.Domain.Integraciones.Persona", b =>
                {
                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<DateTime>("ActualizadoEnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ConsultadoReniecEnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FirstLastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("FuenteUltimaActualizacion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text");

                    b.Property<string>("SecondLastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("NumeroDocumento");

                    b.ToTable("Personas", (string)null);
                });

            modelBuilder.Entity("KallpaNexus.Domain.Integraciones.TipoCambioSunatCache", b =>
                {
                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BuyPrice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ConsultadoEnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QuoteCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SellPrice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Fecha");

                    b.ToTable("TiposCambioSunat", (string)null);
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Entities.Cancha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("EstaActiva")
                        .HasColumnType("boolean");

                    b.Property<string>("ImagenWebRuta")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TieneIluminacion")
                        .HasColumnType("boolean");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId");

                    b.ToTable("Canchas");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Entities.CanchaTarifa", b =>
                {
                    b.Property<Guid>("CanchaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TarifaCanchaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("CanchaId", "TarifaCanchaId");

                    b.HasIndex("TarifaCanchaId");

                    b.ToTable("CanchasTarifas", (string)null);
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Entities.CompraProducto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<decimal>("CostoTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("CostoUnitario")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductoNombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Proveedor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RegistradoPorNombre")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("SucursalId", "FechaHora");

                    b.ToTable("ComprasProducto", (string)null);
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Entities.ConfiguracionNegocioSport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ImagenHeroRuta")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("MaxReservasWebPorDniPorDia")
                        .HasColumnType("integer");

                    b.Property<string>("MensajeWebLanding")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<string>("MensajeWhatsAppReserva")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("MinutosHoldWeb")
                        .HasColumnType("integer");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("ReservaWebActiva")
                        .HasColumnType("boolean");

                    b.Property<string>("TelefonoWhatsAppNegocio")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TituloWebLanding")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("ConfiguracionNegocio", (string)null);
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Entities.Egreso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MedioPagoId")
                        .HasColumnType("uuid");

                    b.Property<string>("MedioPagoNombre")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("Monto")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RegistradoPorNombre")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId", "FechaHora");

                    b.ToTable("Egresos", (string)null);
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Entities.MedioPagoTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("ConfiguracionIntegracionJson")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("EsPasarelaExterna")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<bool>("PermiteSinVoucherPresencial")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiereVoucherOnline")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("MediosPago", (string)null);
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Entities.PagoReserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Canal")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoOperacion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<Guid>("MedioPagoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<bool>("RegistradoSinVoucher")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ReservaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("VoucherUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("MedioPagoId");

                    b.HasIndex("ReservaId");

                    b.HasIndex("TenantId");

                    b.ToTable("PagosReserva", (string)null);
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Entities.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<bool>("ControlStock")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int?>("PuntoAlerta")
                        .HasColumnType("integer");

                    b.Property<int>("StockActual")
                        .HasColumnType("integer");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("VisibleEnWeb")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId", "Activo");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Entities.ReporteFinancieroArchivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("DatosJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DesdeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GeneradoEnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeneradoPorNombre")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("GeneradoPorStaffId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("HastaUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<string>("SucursalNombre")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GeneradoEnUtc");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Codigo")
                        .IsUnique();

                    b.ToTable("ReportesFinancierosArchivo", (string)null);
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Entities.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("AdelantoDevuelto")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CanceladaEnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CanchaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("HoldExpiraEnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("HoraFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("numeric");

                    b.Property<string>("NombreClienteReserva")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int>("Origen")
                        .HasColumnType("integer");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CanchaId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Reservas", (string)null);
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Entities.ReservaProductoSolicitado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReservaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("ReservaId");

                    b.ToTable("ReservaProductosSolicitados", (string)null);
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Entities.Sucursal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<double?>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TelefonoWhatsApp")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Sucursales", (string)null);
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Entities.TarifaCancha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<bool>("AplicaFinDeSemana")
                        .HasColumnType("boolean");

                    b.Property<bool>("AplicaLunesAViernes")
                        .HasColumnType("boolean");

                    b.Property<int>("HoraFin")
                        .HasColumnType("integer");

                    b.Property<int>("HoraInicio")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PrecioPorHora")
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("TarifasCanchas", (string)null);
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Entities.Venta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClienteNombre")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MedioPagoId")
                        .HasColumnType("uuid");

                    b.Property<string>("MedioPagoNombre")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RegistradoPorNombre")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("ReservaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId", "FechaHora");

                    b.ToTable("Ventas", (string)null);
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Entities.VentaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid?>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductoNombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VentaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VentaId");

                    b.ToTable("VentaItems", (string)null);
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Tenancy.RolTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("EsSistema")
                        .HasColumnType("boolean");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Codigo")
                        .IsUnique();

                    b.ToTable("RolesTenant", (string)null);
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Tenancy.RolTenantPermiso", b =>
                {
                    b.Property<Guid>("RolTenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("PermisoCodigo")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("RolTenantId", "PermisoCodigo");

                    b.ToTable("RolesTenantPermisos", (string)null);
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Tenancy.UsuarioStaff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DebeCambiarPassword")
                        .HasColumnType("boolean");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RolTenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RolTenantId");

                    b.HasIndex("TenantId", "Dni")
                        .IsUnique();

                    b.ToTable("UsuariosStaff", (string)null);
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Tenancy.UsuarioStaffSucursal", b =>
                {
                    b.Property<Guid>("UsuarioStaffId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid");

                    b.HasKey("UsuarioStaffId", "SucursalId");

                    b.HasIndex("SucursalId");

                    b.ToTable("UsuariosStaffSucursales", (string)null);
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Entities.Cancha", b =>
                {
                    b.HasOne("KallpaNexus.Domain.Modulos.Sport.Entities.Sucursal", "Sucursal")
                        .WithMany("Canchas")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Entities.CanchaTarifa", b =>
                {
                    b.HasOne("KallpaNexus.Domain.Modulos.Sport.Entities.Cancha", "Cancha")
                        .WithMany()
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KallpaNexus.Domain.Modulos.Sport.Entities.TarifaCancha", "TarifaCancha")
                        .WithMany()
                        .HasForeignKey("TarifaCanchaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cancha");

                    b.Navigation("TarifaCancha");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Entities.PagoReserva", b =>
                {
                    b.HasOne("KallpaNexus.Domain.Modulos.Sport.Entities.MedioPagoTenant", "MedioPago")
                        .WithMany()
                        .HasForeignKey("MedioPagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KallpaNexus.Domain.Modulos.Sport.Entities.Reserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedioPago");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Entities.Reserva", b =>
                {
                    b.HasOne("KallpaNexus.Domain.Modulos.Sport.Entities.Cancha", "Cancha")
                        .WithMany()
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KallpaNexus.Domain.Entities.Compartido.Cliente", "Cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cancha");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Entities.ReservaProductoSolicitado", b =>
                {
                    b.HasOne("KallpaNexus.Domain.Modulos.Sport.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KallpaNexus.Domain.Modulos.Sport.Entities.Reserva", "Reserva")
                        .WithMany("ProductosSolicitados")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Entities.VentaItem", b =>
                {
                    b.HasOne("KallpaNexus.Domain.Modulos.Sport.Entities.Venta", null)
                        .WithMany("Items")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Tenancy.RolTenantPermiso", b =>
                {
                    b.HasOne("KallpaNexus.Domain.Modulos.Sport.Tenancy.RolTenant", "RolTenant")
                        .WithMany("Permisos")
                        .HasForeignKey("RolTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RolTenant");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Tenancy.UsuarioStaff", b =>
                {
                    b.HasOne("KallpaNexus.Domain.Modulos.Sport.Tenancy.RolTenant", "RolTenant")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolTenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RolTenant");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Tenancy.UsuarioStaffSucursal", b =>
                {
                    b.HasOne("KallpaNexus.Domain.Modulos.Sport.Entities.Sucursal", null)
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KallpaNexus.Domain.Modulos.Sport.Tenancy.UsuarioStaff", "UsuarioStaff")
                        .WithMany("SucursalesAsignadas")
                        .HasForeignKey("UsuarioStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioStaff");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Entities.Compartido.Cliente", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Entities.Reserva", b =>
                {
                    b.Navigation("ProductosSolicitados");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Entities.Sucursal", b =>
                {
                    b.Navigation("Canchas");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Entities.Venta", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Tenancy.RolTenant", b =>
                {
                    b.Navigation("Permisos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Modulos.Sport.Tenancy.UsuarioStaff", b =>
                {
                    b.Navigation("SucursalesAsignadas");
                });
#pragma warning restore 612, 618
        }
    }
}
