// <auto-generated />
using System;
using KallpaNexus.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KallpaNexus.Infrastructure.Migrations
{
    [DbContext(typeof(MasterDbContext))]
    [Migration("20260520193313_UsuariosPlataforma")]
    partial class UsuariosPlataforma
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KallpaNexus.Domain.Tenancy.ClienteEmpresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DireccionFiscal")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("DocumentoFiscal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EmailFacturacion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("PlanSaaSId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ProximoPago")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoFiscal")
                        .IsUnique();

                    b.HasIndex("PlanSaaSId");

                    b.ToTable("ClientesEmpresas", "admin");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Tenancy.PlanSaaS", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("LimiteSucursales")
                        .HasColumnType("integer");

                    b.Property<int>("LimiteUsuariosStaff")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PrecioMensual")
                        .HasColumnType("numeric(12,2)");

                    b.Property<bool>("SoportaFidelizacionPuntos")
                        .HasColumnType("boolean");

                    b.Property<bool>("SoportaModuloCare")
                        .HasColumnType("boolean");

                    b.Property<bool>("SoportaModuloSport")
                        .HasColumnType("boolean");

                    b.Property<bool>("SoportaModuloStay")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("PlanesSaaS", "admin");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Tenancy.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteEmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConnectionString")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("NombreComercialNegocio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteEmpresaId");

                    b.HasIndex("Subdomain")
                        .IsUnique();

                    b.ToTable("Tenants", "admin");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Tenancy.UsuarioPlataforma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("UsuariosPlataforma", "admin");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Tenancy.ClienteEmpresa", b =>
                {
                    b.HasOne("KallpaNexus.Domain.Tenancy.PlanSaaS", "PlanSaaS")
                        .WithMany("ClientesEmpresas")
                        .HasForeignKey("PlanSaaSId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlanSaaS");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Tenancy.Tenant", b =>
                {
                    b.HasOne("KallpaNexus.Domain.Tenancy.ClienteEmpresa", "ClienteEmpresa")
                        .WithMany("Tenants")
                        .HasForeignKey("ClienteEmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClienteEmpresa");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Tenancy.ClienteEmpresa", b =>
                {
                    b.Navigation("Tenants");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Tenancy.PlanSaaS", b =>
                {
                    b.Navigation("ClientesEmpresas");
                });
#pragma warning restore 612, 618
        }
    }
}
