// <auto-generated />
using System;
using KallpaNexus.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KallpaNexus.Infrastructure.Migrations
{
    [DbContext(typeof(MasterDbContext))]
    partial class MasterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KallpaNexus.Domain.Tenancy.ClienteEmpresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DireccionFiscal")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("DocumentoFiscal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EmailFacturacion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("PlanSaaSId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ProximoPago")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoFiscal")
                        .IsUnique();

                    b.HasIndex("PlanSaaSId");

                    b.ToTable("ClientesEmpresas", "admin");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Tenancy.Permiso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Permisos", "admin");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Tenancy.PlanSaaS", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("DiasDuracionDemo")
                        .HasColumnType("integer");

                    b.Property<int>("LimiteSucursales")
                        .HasColumnType("integer");

                    b.Property<int>("LimiteUsuariosStaff")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PrecioMensual")
                        .HasColumnType("numeric(12,2)");

                    b.Property<bool>("SoportaFidelizacionPuntos")
                        .HasColumnType("boolean");

                    b.Property<bool>("SoportaModuloCare")
                        .HasColumnType("boolean");

                    b.Property<bool>("SoportaModuloSport")
                        .HasColumnType("boolean");

                    b.Property<bool>("SoportaModuloStay")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("PlanesSaaS", "admin");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Tenancy.RolPlataforma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("EsSistema")
                        .HasColumnType("boolean");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("RolesPlataforma", "admin");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Tenancy.RolPlataformaPermiso", b =>
                {
                    b.Property<Guid>("RolPlataformaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermisoId")
                        .HasColumnType("uuid");

                    b.HasKey("RolPlataformaId", "PermisoId");

                    b.HasIndex("PermisoId");

                    b.ToTable("RolesPlataformaPermisos", "admin");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Tenancy.SolicitudContratoPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteEmpresaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<string>("MensajeCliente")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("NotasPlataforma")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("PlanSaaSId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RespondidoEn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SolicitanteDni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SolicitanteEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SolicitanteNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Subdomain")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanSaaSId");

                    b.HasIndex("ClienteEmpresaId", "Estado");

                    b.ToTable("SolicitudesContratoPlan", "admin");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Tenancy.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteEmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConnectionString")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("NombreComercialNegocio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteEmpresaId");

                    b.HasIndex("Subdomain")
                        .IsUnique();

                    b.ToTable("Tenants", "admin");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Tenancy.UsuarioConsumidor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("UsuariosConsumidor", "admin");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Tenancy.UsuarioPlataforma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("Oculto")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RolPlataformaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Oculto");

                    b.HasIndex("RolPlataformaId");

                    b.ToTable("UsuariosPlataforma", "admin");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Tenancy.ClienteEmpresa", b =>
                {
                    b.HasOne("KallpaNexus.Domain.Tenancy.PlanSaaS", "PlanSaaS")
                        .WithMany("ClientesEmpresas")
                        .HasForeignKey("PlanSaaSId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlanSaaS");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Tenancy.RolPlataformaPermiso", b =>
                {
                    b.HasOne("KallpaNexus.Domain.Tenancy.Permiso", "Permiso")
                        .WithMany("Roles")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KallpaNexus.Domain.Tenancy.RolPlataforma", "RolPlataforma")
                        .WithMany("Permisos")
                        .HasForeignKey("RolPlataformaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("RolPlataforma");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Tenancy.SolicitudContratoPlan", b =>
                {
                    b.HasOne("KallpaNexus.Domain.Tenancy.ClienteEmpresa", "ClienteEmpresa")
                        .WithMany()
                        .HasForeignKey("ClienteEmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KallpaNexus.Domain.Tenancy.PlanSaaS", "PlanSaaS")
                        .WithMany()
                        .HasForeignKey("PlanSaaSId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClienteEmpresa");

                    b.Navigation("PlanSaaS");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Tenancy.Tenant", b =>
                {
                    b.HasOne("KallpaNexus.Domain.Tenancy.ClienteEmpresa", "ClienteEmpresa")
                        .WithMany("Tenants")
                        .HasForeignKey("ClienteEmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClienteEmpresa");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Tenancy.UsuarioPlataforma", b =>
                {
                    b.HasOne("KallpaNexus.Domain.Tenancy.RolPlataforma", "RolPlataforma")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolPlataformaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RolPlataforma");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Tenancy.ClienteEmpresa", b =>
                {
                    b.Navigation("Tenants");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Tenancy.Permiso", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Tenancy.PlanSaaS", b =>
                {
                    b.Navigation("ClientesEmpresas");
                });

            modelBuilder.Entity("KallpaNexus.Domain.Tenancy.RolPlataforma", b =>
                {
                    b.Navigation("Permisos");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
