/** Clases semánticas — colores vía CSS variables (tema claro / oscuro). */
export const platformUi = {
  pageTitle: "platform-page-title",
  pageTitleHero: "platform-page-title-hero",
  pageSubtitle: "platform-page-subtitle",
  sectionTitle: "platform-section-title",
  card: "platform-card",
  cardInner: "platform-card-inner",
  kpiValue: "platform-kpi-value",
  kpiLabel: "platform-kpi-label",
  tableWrap: "platform-table-wrap",
  tableHead: "platform-table-head",
  tableRow: "platform-table-row",
  th: "px-4 py-3 font-medium",
  td: "px-4 py-3",
  textMuted: "platform-text-muted",
  textBody: "platform-text-body",
  formLabel: "platform-form-label",
  link: "platform-link",
  btnPrimary: "platform-btn-primary disabled:opacity-50",
  btnSecondary: "platform-btn-secondary disabled:opacity-50",
  input: "platform-input",
  badgeOk: "platform-badge-ok",
  badgeMuted: "platform-badge-muted",
  badgeWarn: "platform-badge-warn",
  badgeDanger: "platform-badge-danger",
  tabActive: "platform-tab-active",
  tabIdle: "platform-tab-idle",
  tabsBar: "platform-tabs-bar",
  modalOverlay: "platform-modal-overlay",
  modal: "platform-modal",
  fieldset: "platform-fieldset",
  alertDanger: "platform-alert-danger",
  alertWarn: "platform-alert-warn",
  alertOk: "platform-alert-ok",
  loginPage: "platform-login-page",
  loginCard: "platform-login-card",
};
